basePath: /api/v1
definitions:
  models.Expense:
    properties:
      amount:
        type: number
      createdAt:
        type: string
      expenseID:
        type: integer
      expenseType:
        $ref: '#/definitions/models.ExpenseType'
      status:
        $ref: '#/definitions/models.ExpenseStatus'
    type: object
  models.ExpenseStatus:
    enum:
    - Paid
    - Covered
    - Unpaid
    type: string
    x-enum-varnames:
    - PaidStatus
    - CoveredStatus
    - UnpaidStatus
  models.ExpenseSummary:
    properties:
      herAmount:
        type: number
      myAmount:
        type: number
      status:
        type: string
    type: object
  models.ExpenseType:
    properties:
      createdAt:
        type: string
      splitType:
        $ref: '#/definitions/models.SplitType'
      typeName:
        type: string
    type: object
  models.Split:
    properties:
      createdAt:
        type: string
      herPercentage:
        type: number
      myPercentage:
        type: number
      splitID:
        type: integer
    type: object
  models.SplitSpecifier:
    properties:
      herNetIncome:
        type: number
      herPercentage:
        type: number
      myNetIncome:
        type: number
      myPercentage:
        type: number
    type: object
  models.SplitType:
    enum:
    - FiftyFifty
    - Default
    - MeOnly
    - HerOnly
    type: string
    x-enum-varnames:
    - FiftyFiftySplit
    - DefaultSplit
    - MeOnlySplit
    - HerOnlySplit
host: localhost:8080
info:
  contact: {}
  description: Manages expense sharing
  title: Rent Cat
  version: "1.0"
paths:
  /expense-summary/{year}/{month}:
    get:
      consumes:
      - application/json
      description: gets expense summary for a certain month and year
      parameters:
      - description: current year
        in: path
        name: year
        required: true
        type: string
      - description: current month
        in: path
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ExpenseSummary'
      summary: gets expense summary for a certain month and year
      tags:
      - expenses
  /expense/{expense_type}/{year}/{month}:
    get:
      consumes:
      - application/json
      description: gets expenses for a certain month and year
      parameters:
      - description: expense type
        in: path
        name: expense_type
        required: true
        type: string
      - description: current year
        in: path
        name: year
        required: true
        type: string
      - description: current month
        in: path
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Expense'
      summary: gets expenses for a certain month and year
      tags:
      - expenses
  /expenses/{year}/{month}:
    get:
      consumes:
      - application/json
      description: gets expenses for a certain month and year
      parameters:
      - description: current year
        in: path
        name: year
        required: true
        type: string
      - description: current month
        in: path
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Expense'
            type: array
      summary: gets expenses for a certain month and year
      tags:
      - expenses
  /split:
    post:
      consumes:
      - application/json
      description: adds expense split percentage
      parameters:
      - description: Split Descriptor
        in: body
        name: Split
        required: true
        schema:
          $ref: '#/definitions/models.SplitSpecifier'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Split'
      summary: adds expense split percentage
      tags:
      - split
  /split/latest:
    get:
      consumes:
      - application/json
      description: gets latest expense split percentage
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Split'
      summary: gets latest expense split percentage
      tags:
      - split
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
